[12.0][IMP] connector_ebisumart: add latest fetch date
qrtl/sbt-custom pull request #5
Opened 2024-01-12 06:35 UTC by AungKoKoLin1997

2024-01-12 15:11 UTC, yostashiro requested changes

2024-01-12 15:11 UTC, yostashiro commented on connector_ebisumart/models/ebisumart_backend.py
> +    latest_fetch_order_data_date = fields.Datetime()
My preferences.

```suggestion
    last_fetch_product_date = fields.Datetime()
    last_fetch_order_date = fields.Datetime()
```

2024-01-12 15:11 UTC, yostashiro commented on connector_ebisumart/models/ebisumart_product_product.py
> +            ]
Why not create a common method in `ebisumart.adapter` and just call the method here, instead of repeating this chunk twice in different places.

2024-01-12 15:11 UTC, yostashiro commented on connector_ebisumart/models/ebisumart_product_product.py
> +                            "value": latest_fetch_date_str
Put this in a variable to make the code a bit more concise.

2024-01-12 15:11 UTC, yostashiro commented on connector_ebisumart/models/ebisumart_product_product.py
> +            latest_fetch_date_str = fetch_date.strftime('%Y/%m/%d %H:%M:%S')
Consider adding a buffer to prevent fetching failures due to server time misalignment or misconfiguration.  Check with @kanda999 on this.

2024-01-15 04:07 UTC, yostashiro commented on connector_ebisumart/components/ebisumart_adapter.py
> +    def _get_filters(self, last_fetch_date):
To make the scope of the method a bit clearer.
```suggestion
    def _get_date_filters(self, last_fetch_date):
```

2024-01-15 05:39 UTC, yostashiro approved these changes
Code review (partial).

2024-01-15 10:27 UTC, kanda999 requested changes

2024-01-15 10:27 UTC, kanda999 commented on connector_ebisumart/components/ebisumart_adapter.py
> +        }
```suggestion
```
I don't think `regist_date_filter` is necessary. Why have this?
The following scenarios are causing problems.
- Create order on 1/12 
- Cancel order on 1/14 
- Import order into Odoo on 1/15
In this case, UPDATE_DATE is 1/14, but REGIST_DATE is 1/12.

2024-01-16 09:15 UTC, kanda999 approved these changes
We tried the following situations 
- Case where ebisumart orders were cancelled from the beginning 
- Case where orders were imported and then cancelled.

Both are working well.

2024-01-16 13:09 UTC, yostashiro commented on connector_ebisumart/models/ebisumart_sale_order.py
> +            [('origin', '=', self.name)]
To be safe.
```suggestion
            [('origin', '=', self.name)], limit=1
```

2024-03-08 10:22 UTC, merged